//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveSync.DatabaseLayer.Dapper.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveSync.DatabaseLayer.Dapper.Dashboard.DashboardResource", typeof(DashboardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    COUNT(*) OVER() AS TotalRecords,
        ///    a.Id,
        ///    d.Name,
        ///    d.StaffIdNum,
        ///    v.PlateNumber AS VehicleNumber,
        ///    d.Age,
        ///    d.MobileNumber,
        ///    d.EmiratesId,
        ///    d.PassportNum,
        ///    d.JoiningDate,
        ///    a.StartDateTime,
        ///    a.EndDateTime,
        ///    a.Status,
        ///    a.Remarks
        ///FROM Assignments a
        ///JOIN Driver d ON a.DriverId = d.Id
        ///JOIN Vehicle v ON a.VehicleId = v.Id
        ///WHERE 
        ///    d.Deleted = 0 
        ///    AND v.Deleted = 0
        ///    AND (
        ///        @searchText IS NULL OR
        ///        d.Name LIKE &apos;%&apos; + @search [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getAllAssignments {
            get {
                return ResourceManager.GetString("getAllAssignments", resourceCulture);
            }
        }
    }
}
