CREATE TABLE Fines
(
	Id BIGINT PRIMARY KEY IDENTITY(1,1),
	DriverId BIGINT NOT NULL,
	VehicleId BIGINT NOT NULL,
	ViolationType NVARCHAR(100) NOT NULL,
	ReceiptNumber NVARCHAR(50) NOT NULL,
	FineNumber NVARCHAR(50) NOT NULL,
	Amount DECIMAL(10, 2) NOT NULL,
	Reason NVARCHAR(255) NULL,
	IssuedDate DATETIMEOFFSET NOT NULL,
	Paid INT NOT NULL DEFAULT 0,
	PaidDate DATE  NULL,
	CreatedDateTime DATETIMEOFFSET NOT NULL,
	UpdatedDateTime DATETIMEOFFSET NOT NULL,
	"Deleted" INT NOT NULL DEFAULT 0

	CONSTRAINT Foreign_Key_Fines_Driver FOREIGN KEY (DriverId) REFERENCES Driver(Id),
	CONSTRAINT Foreign_Key_Fines_Vehicle FOREIGN KEY (VehicleId) REFERENCES Vehicle(Id)
);