CREATE TABLE RentalCompanies
(
	"Id" BIGINT IDENTITY(1,1) PRIMARY KEY,
	"CompanyName" VARCHAR(255) NOT NULL,
	"ContactNumber" BIGINT NOT NULL,
	"Address" VARCHAR(500) NULL,
	"Status" INT NOT NULL,
	"CreatedDateTime" DATETIMEOFFSET NOT NULL,
	"UpdatedDateTime" DATETIMEOFFSET NOT NULL,
	"Remarks" VARCHAR(255) NULL,
	"Deleted" INT NOT NULL DEFAULT 0
);