//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveSync.DatabaseLayer.Dapper.Fines {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FineResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FineResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveSync.DatabaseLayer.Dapper.Fines.FineResource", typeof(FineResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    d.Name,
        ///    d.StaffIdNum,
        ///    f.FineNumber,
        ///    f.Amount,
        ///    f.ViolationType,
        ///    f.Reason,
        ///    f.IssuedDate,
        ///    v.PlateNumber,
        ///    f.Paid
        ///FROM 
        ///    Fines f
        ///JOIN Driver d ON f.DriverId = d.Id    
        ///JOIN Vehicle v ON f.VehicleId = v.Id
        ///WHERE 
        ///    (@status IS NULL OR f.Paid = @status) 
        ///    AND (
        ///        @searchText IS NULL OR
        ///        d.StaffIdNum LIKE &apos;%&apos; + @searchText + &apos;%&apos; OR
        ///        d.Name LIKE &apos;%&apos; + @searchText + &apos;%&apos;
        ///    )
        ///    AND (
        ///        @fromDate IS NULL OR @toDate IS [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FineReport {
            get {
                return ResourceManager.GetString("FineReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///    COUNT(*) OVER() AS TotalRecords,
        ///f.Id,
        ///f.FineNumber,
        ///f.Amount,
        ///f.ReceiptNumber,
        ///f.IssuedDate,
        ///f.ViolationType,
        ///f.Paid,
        ///f.PaidDate,
        ///f.Reason,
        ///d.Name AS DriverName,
        ///v.PlateNumber AS VehiclePlateNumber
        ///FROM Fines f
        ///JOIN Driver d ON f.DriverId = d.Id
        ///JOIN Vehicle v ON f.VehicleId = v.Id
        ///WHERE 
        ///        @searchText IS NULL OR
        ///        d.Name LIKE &apos;%&apos; + @searchText + &apos;%&apos; OR
        ///        v.PlateNumber LIKE &apos;%&apos; + @searchText + &apos;%&apos; OR
        ///        f.FineNumber LIKE &apos;%&apos; + @searchText + &apos;%&apos;
        ///ORDER  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string getFines {
            get {
                return ResourceManager.GetString("getFines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///Id,
        ///PlateNumber
        ///FROM Vehicle 
        ///WHERE DELETED = 0
        ///.
        /// </summary>
        public static string getvehicles_fines {
            get {
                return ResourceManager.GetString("getvehicles_fines", resourceCulture);
            }
        }
    }
}
