CREATE TABLE "Assignments"
(
"Id" BIGINT IDENTITY(1,1) PRIMARY KEY,
"DriverId" BIGINT NOT NULL,
"VehicleId" BIGINT NOT NULL,
"StartDateTime" DATETIMEOFFSET NOT NULL,
"EndDateTime" DATETIMEOFFSET NULL,
"CreatedDateTime" DATETIMEOFFSET NOT NULL,
"UpdatedDateTime" DATETIMEOFFSET NOT NULL,
"Comments" VARCHAR(MAX) NULL,
"Remarks" VARCHAR(MAX) NULL,
"Status" SMALLINT NOT NULL,
CONSTRAINT FK_Vehicle_VehicleId FOREIGN KEY ("VehicleId") REFERENCES "Vehicle"("Id"),
CONSTRAINT FK_Driver_DriverId FOREIGN KEY ("DriverId") REFERENCES "Driver"("Id")
)