//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveSync.DatabaseLayer.Dapper.Drivers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DriverResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DriverResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveSync.DatabaseLayer.Dapper.Drivers.DriverResource", typeof(DriverResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT
        /// d.Id,
        /// d.Name,
        /// d.Age,
        /// d.StaffIdNum,
        /// d.Email,
        /// d.MobileNumber,
        /// d.AlternateMobileNumber,
        /// d.EmiratesId,
        /// d.PassportNum,
        /// lt.Type AS &quot;LicenseType&quot;,
        /// ez.Zone AS &quot;EmirateZone&quot;,
        ///  d.LicenseNumber,
        /// d.LicenseExpiryDate,
        /// d.JoiningDate,
        /// d.ResignationDate,
        /// d.VacationDateFrom,
        /// d.VacationDateTo,
        /// d.Status,
        /// d.CreatedDateTime,
        /// d.UpdatedDateTime,
        /// d.Deleted,
        /// d.Remarks
        ///FROM Driver d
        ///JOIN LicenseType lt ON lt.Id = d.LicenseTypeId
        ///JOIN EmirateZone ez ON ez.Id = d.EmiratesZoneId
        ///W [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DriverReport {
            get {
                return ResourceManager.GetString("DriverReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  SELECT
        ///     COUNT(*) OVER() AS TotalRecords,
        ///     SUM(CASE WHEN d.Status = 1 THEN 1 ELSE 0 END) OVER() AS AvailableCount,
        /// d.Id,
        /// d.Name,
        /// d.Age,
        /// d.StaffIdNum,
        /// d.Email,
        /// d.MobileNumber,
        /// d.AlternateMobileNumber,
        /// d.EmiratesId,
        /// d.PassportNum,
        /// lt.Type AS &quot;LicenseType&quot;,
        /// ez.Zone AS &quot;EmirateZone&quot;,
        ///  d.LicenseNumber,
        /// d.LicenseExpiryDate,
        /// d.JoiningDate,
        /// d.ResignationDate,
        /// d.VacationDateFrom,
        /// d.VacationDateTo,
        /// d.Status,
        /// d.CreatedDateTime,
        /// d.UpdatedDateTime,
        /// d.Deleted,
        /// d.Remar [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetDrivers {
            get {
                return ResourceManager.GetString("GetDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///COUNT(*) AS TotalDrivers,
        ///SUM(CASE WHEN Status = 1 THEN 1 ELSE 0 END) AS DriverAvailableCount,
        ///SUM(CASE WHEN Status = 2 THEN 1 ELSE 0 END) AS DriverAssignedCount,
        ///SUM(CASE WHEN Status = 3 THEN 1 ELSE 0 END) AS DriverSickCount,
        ///SUM(CASE WHEN Status = 4 THEN 1 ELSE 0 END) AS DriverOnVacationCount
        ///FROM Driver
        ///WHERE Deleted = 0.
        /// </summary>
        public static string getDriversCount {
            get {
                return ResourceManager.GetString("getDriversCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///Id,
        ///Name
        ///FROM Driver
        ///WHERE Status = 1 AND Deleted = 0 
        ///.
        /// </summary>
        public static string GetDropdownDrivers {
            get {
                return ResourceManager.GetString("GetDropdownDrivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM EmirateZone.
        /// </summary>
        public static string GetEmirateZone {
            get {
                return ResourceManager.GetString("GetEmirateZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM LicenseType.
        /// </summary>
        public static string GetLicenseTypes {
            get {
                return ResourceManager.GetString("GetLicenseTypes", resourceCulture);
            }
        }
    }
}
