//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DriveSync.DatabaseLayer.Dapper.Vehicle {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class VehicleResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VehicleResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DriveSync.DatabaseLayer.Dapper.Vehicle.VehicleResource", typeof(VehicleResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///Id,
        ///PlateNumber
        ///FROM Vehicle 
        ///WHERE Status = 1 AND Deleted =0 AND MulkiyaExpiryDate &gt;= GETDATE().
        /// </summary>
        public static string GetDropdownVehicles {
            get {
                return ResourceManager.GetString("GetDropdownVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT v.Id,
        ///v.PlateNumber,
        ///v.Model,
        ///vt.Type,
        ///rc.CompanyName,
        ///v.Status,
        ///v.MulkiyaExpiryDate,
        ///v.CreatedDateTime,
        ///v.UpdatedDateTime,
        ///v.Remarks
        ///FROM Vehicle v
        ///JOIN VehicleType vt ON v.VehicleTypeId = vt.Id
        ///JOIN RentalCompanies rc ON v.RentalCompanyId = rc.Id 
        ///WHERE v.Deleted =0.
        /// </summary>
        public static string GetVehicles {
            get {
                return ResourceManager.GetString("GetVehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM VehicleType.
        /// </summary>
        public static string GetVehicleTypes {
            get {
                return ResourceManager.GetString("GetVehicleTypes", resourceCulture);
            }
        }
    }
}
